In [285]:
# 라이브러리 import
import numpy as np
import pandas as pd

In [286]:
# 배치 경사 하강법
def stochastic_gradient_descent(x : np.ndarray, y : np.ndarray, theta : np.ndarray, alpha : float, m, epoch : int, batchSize):
	# 특성을 pivot 한다. [[키, 몸무게], [키, 몸무게]] -> [[키, 키], [몸무게, 몸무게]]
    xTrans = x.transpose()
    # 에포크만큼 반복문을 돌린다. 
    for i in range(0, epoch):
    	# 가설을 세운다.
        hypothesis = np.dot(x, theta)
        # 가설과 라벨(실제 결과값)을 비교하여 손실을 구한다.
        loss = hypothesis - y
        # 비용을 구한다.
        cost = np.sum(loss ** 2) / (2 * m)
        # 경사를 구한다.
        gradient = np.dot(xTrans, loss) / m
        # 가중치를 업데이트한다.
        theta = theta - alpha * gradient
    # 결과를 리턴한다.
    return ("배치" , cost, theta)

In [287]:
# 데이터 로드
df = pd.read_csv('data/byong_data_set1.csv')
df.head()

bmi  height  weight
0  26.1   172.3    77.5
1  29.5   172.6    88.0
2  25.2   170.6    73.5
3  22.9   173.0    68.6
4  21.4   172.1    63.6

In [288]:
# 데이터 세팅
x = df[['height', 'weight']].values # 특성 (feature)
x

array([[172.3,  77.5],
       [172.6,  88. ],
       [170.6,  73.5],
       ...,
       [177.5,  82.4],
       [191.6, 116.1],
       [171.4,  68. ]])

In [289]:
y = df[['bmi']].values # 라벨 (label)
y

array([[26.1],
       [29.5],
       [25.2],
       ...,
       [26.1],
       [31.6],
       [23.1]])

In [290]:
m, n = np.shape(x)
print(m)
print(n)

217000
2


In [291]:
epoch = 5 # 에포크 (epoch)

In [292]:
theta = np.ones(n).reshape(-1, 1) # 임의 가중치
theta

array([[1.],
       [1.]])

In [293]:
alpha = 0.00001 # 학습률

In [294]:
batchSize = 100 # 미니 배치 크기

In [295]:
x

array([[172.3,  77.5],
       [172.6,  88. ],
       [170.6,  73.5],
       ...,
       [177.5,  82.4],
       [191.6, 116.1],
       [171.4,  68. ]])

In [296]:
# 특성을 pivot 한다. [[키, 몸무게], [키, 몸무게]] -> [[키, 키], [몸무게, 몸무게]]
xTrans = x.transpose()
xTrans

array([[172.3, 172.6, 170.6, ..., 177.5, 191.6, 171.4],
       [ 77.5,  88. ,  73.5, ...,  82.4, 116.1,  68. ]])

In [297]:
y

array([[26.1],
       [29.5],
       [25.2],
       ...,
       [26.1],
       [31.6],
       [23.1]])

In [298]:
# 가설을 세운다.
hypothesis = np.dot(x, theta)
hypothesis

array([[249.8],
       [260.6],
       [244.1],
       ...,
       [259.9],
       [307.7],
       [239.4]])

In [299]:
# 가설과 라벨(실제 결과값)을 비교하여 손실을 구한다.
loss = hypothesis - y
loss

array([[223.7],
       [231.1],
       [218.9],
       ...,
       [233.8],
       [276.1],
       [216.3]])

In [300]:
# 비용을 구한다.
cost = np.sum(loss ** 2) / (2 * m)
cost

25054.603702695855

In [301]:
# 경사를 구한다.
gradient = alpha * np.dot(xTrans, loss) / m
gradient

array([[0.38991081],
       [0.16512499]])

In [302]:
# 가중치를 업데이트한다.
theta = theta - gradient
theta

array([[0.61008919],
       [0.83487501]])

In [305]:
a = np.array([[1, 2]])
b = np.array([[2], [5]])
# a의 열의 수와 b의 행의 수가 같아야 한다.
# a의 각 열과 b의 각 행을 곱한 후 더한다.
np.dot(a, b)

array([[12]])

In [ ]:
a = np.array([[2, 2, 2, 2, 2], [5, 4, 3, 2, 1]])
b = np.array([[1], [1], [1], [1], [1]])
# a의 열의 수와 b의 행의 수가 같아야 한다.
# a의 각 열과 b의 각 행을 곱한 후 더한다.
np.dot(a, b) / 5
# 나누는 값은 데이터의 개수이다.